await 0

throw new Error('async-child-error');
